<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net462;net8.0-windows</TargetFrameworks>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<AssemblyTitle>DocxToHtml</AssemblyTitle>
		<Product>DocxToHtml</Product>
		<ApplicationIcon>geek.ico</ApplicationIcon>
		<UseWindowsForms>true</UseWindowsForms>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>..\DocxToHtml.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Master.cs">
			<SubType>Form</SubType>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\DocxToHtml.Converter\DocxToHtml.Converter.csproj" />
		<ProjectReference Include="..\HtmlToDocx.Converter\HtmlToDocx.Converter.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="EditorInit.Html">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="geek.ico" />
	</ItemGroup>
</Project>